import { TerminalConfig, IndicatorConfig, TradeAxisConfig, StrategyConfig } from './types';

export const DEFAULT_CONFIG: TerminalConfig = {
    symbol: 'GLD',
    // resolution is always '1m' — hardcoded, not persisted
    mode: 'random',
    startDate: '2023-01-01',
    endDate: '2024-01-01',
    years: 1,
    months: 0,
    days: 0,
};

export const DEFAULT_INDICATOR_CONFIG: IndicatorConfig = {
    rsi_period: 14,
    macd_fast: 12,
    macd_slow: 26,
    macd_signal: 9,
    bb_period: 20,
    bb_std: 2.0,
    adx_period: 14,
    atr_period: 14,
    sma_period: 200,
};

export const DEFAULT_TRADEAXIS_CONFIG: TradeAxisConfig = {
    touchZone: 0.2,
    profitProtection: 1.0,
    windowSize: 5,
    tolerance: 0.005,
    minPivots: 2,
    proximity: 0.25,
    useErrorFilter: false,
    errorRate: 0.05,
    filterBestFit: true,
    bestFitUseAnchorGrouping: true,
    bestFitUseNMS: true,
    bestFitAnchorSlopeTolerance: 0.05,
    bestFitNmsPriceTolerance: 0.005,
    bestFitNmsSlopeTolerance: 0.15,
    bestFitNmsLevelSlopeCutoff: 0.01,
    bestFitNmsLevelTolerance: 0.001,
    useAngleFilter: true,
    maxAngle: 45,
    minAngle: -45,
    useProfitProtection: true,
    useTouchDetection: true,
    useBreakoutDetection: true,
    useZoneExit: true,
    useStopLoss: false,
    useTakeProfit: false,
    useWindowSizeRule: true,
    windowSizeUseFirstMinute: true,
    usePriceChangeRule: true,
    priceChangeThreshold: 0.02,
    useZoneBounce: false,
};

export const DEFAULT_STRATEGY_CONFIG: StrategyConfig = {
    longThreshold: 65,
    shortThreshold: 35,
    stopLoss: 2.0,
    takeProfit: 4.0,
    initialEquity: 100000,
    riskPerTrade: 10,
    leverage: 1,
    exitThreshold: 20,
    preHistoryBars: 200,
    trendScoreTimeWeight: 1,
    trendScorePivotWeight: 1,
    trendScoreClosenessWeight: 1,
    trendScoreSlopeWeight: 1,
    trendScoreClosenessPct: 2,
    trendScoreSlopeRef: 0.02,
    useClosestFilter: true,
    closestFilterCount: 4,
    useMostValuableFilter: true,
    mostValuableFilterCount: 4,
};
